In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.preprocessing import OrdinalEncoder

In [47]:
train_df = pd.read_table("train.tsv")
train_df = shuffle(train_df)
print(train_df.shape)
train_df.head(5)

(150211, 13)


Number_of_Shops_Around_ATM ATM_Zone  No_of_Other_ATMs_in_1_KM_radius  \
92817                         163       RM                               21   
40960                          66       RL                              100   
67108                          71       RM                               60   
10703                         121       RM                               32   
35739                         126       FV                               59   

       Estimated_Number_of_Houses_in_1_KM_Radius ATM_Placement    ATM_TYPE  \
92817                                       1680   Facing Road       Urban   
40960                                      13000   Facing Road       Urban   
67108                                       7740   Facing Road       Urban   
10703                                       4500   Facing Road       Urban   
35739                                       4282   Facing Road  Semi Urban   

      ATM_Location_TYPE ATM_looks ATM_Attached_to  Average_Wait_Time Day_Type  \
92817     Only WIthdraw    Normal        Building                  2  Working   
40960     Only WIthdraw    Normal        Building                  4  Working   
67108     Only WIthdraw    Normal        Building                  3  Working   
10703     Only WIthdraw    Normal     Petrol Bunk                  2  Working   
35739     Only WIthdraw    Normal        Building                  2  Working   

       rating  revenue  
92817       3   105600  
40960       4   197300  
67108       3   132400  
10703       3   170100  
35739       4   201400

In [48]:
test_df = pd.read_table("test.tsv")
print(test_df.shape)
test_df.head(5)

(2836, 13)


Number_of_Shops_Around_ATM ATM_Zone  No_of_Other_ATMs_in_1_KM_radius  \
0                          81       RL                              101   
1                          30       RL                               78   
2                          24       RL                               87   
3                          66       RL                               51   
4                          57       RL                               80   

   Estimated_Number_of_Houses_in_1_KM_Radius ATM_Placement ATM_TYPE  \
0                                       9150   Facing Road     Town   
1                                       7800   Facing Road    Urban   
2                                       9830   Facing Road     Town   
3                                       8121   Facing Road     Town   
4                                      17120   Facing Road    Urban   

  ATM_Location_TYPE ATM_looks ATM_Attached_to  Average_Wait_Time Day_Type  \
0     Only WIthdraw    Normal        Building                  3  Working   
1     Only WIthdraw    Normal        Building                  2  Working   
2     Only WIthdraw    Normal        Building                  3  Working   
3     Only WIthdraw    Normal        Building                  3  Working   
4     Only WIthdraw    Normal        Building                  4  Working   

   rating  revenue  
0       3   172600  
1       3   133100  
2       4   171700  
3       3   176700  
4       3   138332

In [49]:
train_df.nunique()

Number_of_Shops_Around_ATM                     120
ATM_Zone                                         5
No_of_Other_ATMs_in_1_KM_radius                110
Estimated_Number_of_Houses_in_1_KM_Radius     1073
ATM_Placement                                    2
ATM_TYPE                                         4
ATM_Location_TYPE                                4
ATM_looks                                        3
ATM_Attached_to                                  6
Average_Wait_Time                                8
Day_Type                                         4
rating                                           4
revenue                                      12066
dtype: int64

In [50]:
test_df.nunique()

Number_of_Shops_Around_ATM                    115
ATM_Zone                                        5
No_of_Other_ATMs_in_1_KM_radius               110
Estimated_Number_of_Houses_in_1_KM_Radius    1073
ATM_Placement                                   2
ATM_TYPE                                        4
ATM_Location_TYPE                               4
ATM_looks                                       3
ATM_Attached_to                                 6
Average_Wait_Time                               8
Day_Type                                        4
rating                                          4
revenue                                      1771
dtype: int64

In [51]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150211 entries, 92817 to 86581
Data columns (total 13 columns):
 #   Column                                     Non-Null Count   Dtype 
---  ------                                     --------------   ----- 
 0   Number_of_Shops_Around_ATM                 150211 non-null  int64 
 1   ATM_Zone                                   150211 non-null  object
 2   No_of_Other_ATMs_in_1_KM_radius            150211 non-null  int64 
 3   Estimated_Number_of_Houses_in_1_KM_Radius  150211 non-null  int64 
 4   ATM_Placement                              150211 non-null  object
 5   ATM_TYPE                                   150211 non-null  object
 6   ATM_Location_TYPE                          150211 non-null  object
 7   ATM_looks                                  150211 non-null  object
 8   ATM_Attached_to                            150211 non-null  object
 9   Average_Wait_Time                          150211 non-null  int64 
 10  Day_Type         

In [52]:
object_fea = train_df.select_dtypes(include=['object']).columns.tolist()
object_fea

['ATM_Zone',
 'ATM_Placement',
 'ATM_TYPE',
 'ATM_Location_TYPE',
 'ATM_looks',
 'ATM_Attached_to',
 'Day_Type']

In [53]:
train_df["ATM_Zone"].unique()

array(['RM', 'RL', 'FV', 'C', 'RH'], dtype=object)

In [54]:
ordinal_encoder = OrdinalEncoder()
train_df[object_fea] = ordinal_encoder.fit_transform(train_df[object_fea]).astype(int)
train_df.head(5)

Number_of_Shops_Around_ATM  ATM_Zone  No_of_Other_ATMs_in_1_KM_radius  \
92817                         163         4                               21   
40960                          66         3                              100   
67108                          71         4                               60   
10703                         121         4                               32   
35739                         126         1                               59   

       Estimated_Number_of_Houses_in_1_KM_Radius  ATM_Placement  ATM_TYPE  \
92817                                       1680              0         3   
40960                                      13000              0         3   
67108                                       7740              0         3   
10703                                       4500              0         3   
35739                                       4282              0         1   

       ATM_Location_TYPE  ATM_looks  ATM_Attached_to  Average_Wait_Time  \
92817                  2          1                0                  2   
40960                  2          1                0                  4   
67108                  2          1                0                  3   
10703                  2          1                3                  2   
35739                  2          1                0                  2   

       Day_Type  rating  revenue  
92817         3       3   105600  
40960         3       4   197300  
67108         3       3   132400  
10703         3       3   170100  
35739         3       4   201400

In [55]:
train_df.nunique()

Number_of_Shops_Around_ATM                     120
ATM_Zone                                         5
No_of_Other_ATMs_in_1_KM_radius                110
Estimated_Number_of_Houses_in_1_KM_Radius     1073
ATM_Placement                                    2
ATM_TYPE                                         4
ATM_Location_TYPE                                4
ATM_looks                                        3
ATM_Attached_to                                  6
Average_Wait_Time                                8
Day_Type                                         4
rating                                           4
revenue                                      12066
dtype: int64

In [56]:
test_df[object_fea] = ordinal_encoder.transform(test_df[object_fea]).astype(int)

In [57]:
test_df.head(5)

Number_of_Shops_Around_ATM  ATM_Zone  No_of_Other_ATMs_in_1_KM_radius  \
0                          81         3                              101   
1                          30         3                               78   
2                          24         3                               87   
3                          66         3                               51   
4                          57         3                               80   

   Estimated_Number_of_Houses_in_1_KM_Radius  ATM_Placement  ATM_TYPE  \
0                                       9150              0         2   
1                                       7800              0         3   
2                                       9830              0         2   
3                                       8121              0         2   
4                                      17120              0         3   

   ATM_Location_TYPE  ATM_looks  ATM_Attached_to  Average_Wait_Time  Day_Type  \
0                  2          1                0                  3         3   
1                  2          1                0                  2         3   
2                  2          1                0                  3         3   
3                  2          1                0                  3         3   
4                  2          1                0                  4         3   

   rating  revenue  
0       3   172600  
1       3   133100  
2       4   171700  
3       3   176700  
4       3   138332

In [64]:
y = np.log(train_df['revenue']).values
y[:5]

array([11.56741365, 12.19248069, 11.79358292, 12.04414178, 12.21304826])

In [65]:
x = train_df.drop('revenue', axis=1).values
x[:5]

array([[  163,     4,    21,  1680,     0,     3,     2,     1,     0,
            2,     3,     3],
       [   66,     3,   100, 13000,     0,     3,     2,     1,     0,
            4,     3,     4],
       [   71,     4,    60,  7740,     0,     3,     2,     1,     0,
            3,     3,     3],
       [  121,     4,    32,  4500,     0,     3,     2,     1,     3,
            2,     3,     3],
       [  126,     1,    59,  4282,     0,     1,     2,     1,     0,
            2,     3,     4]], dtype=int64)

In [76]:
y_test = test_df['revenue'].values
y_test[:5]

array([172600, 133100, 171700, 176700, 138332], dtype=int64)

In [77]:
x_test = test_df.drop('revenue', axis=1).values
x_test[:5]

array([[   81,     3,   101,  9150,     0,     2,     2,     1,     0,
            3,     3,     3],
       [   30,     3,    78,  7800,     0,     3,     2,     1,     0,
            2,     3,     3],
       [   24,     3,    87,  9830,     0,     2,     2,     1,     0,
            3,     3,     4],
       [   66,     3,    51,  8121,     0,     2,     2,     1,     0,
            3,     3,     3],
       [   57,     3,    80, 17120,     0,     3,     2,     1,     0,
            4,     3,     3]], dtype=int64)

In [66]:
split_percentage = 0.8
split_point = int(len(x) * split_percentage)

x_train = x[:split_point]
x_val = x[split_point:]
y_train = y[:split_point]
y_val = y[split_point:]

In [67]:
from sklearn.metrics import mean_squared_error, r2_score

def rmsle(Y, Y_pred):
    assert Y.shape == Y_pred.shape
    return np.sqrt(np.mean(np.square(Y_pred - Y)))

def run_model(model, X_train, y_train, X_val, y_val):
    model.fit(X_train, y_train)
    
    ypre = model.predict(X_val)
    
    mse = mean_squared_error(y_val, ypre)
    r_sq = r2_score(y_val, ypre)
    rmlse_1 = rmsle(y_val, ypre)
    
    print("Mean Squared Error Value : "+"{:.2f}".format(mse))
    print("\nR-Squared Value : "+"{:.2f}".format(r_sq))
    print("\nRMLSE : "+"{:.2f}".format(rmlse_1))
    return model, mse, r_sq, rmlse_1

In [68]:
# from sklearn.linear_model import LinearRegression

# linear_reg = LinearRegression()
# print("Linear Regression")
# print("---------------------------------------")
# model_2, mse_2, r_sq_2, rmlse_3 = run_model(linear_reg, x_train, y_train, x_val, y_val)

Linear Regression
---------------------------------------
Mean Squared Error Value : 0.06

R-Squared Value : 0.58

RMLSE : 0.25


In [70]:
# from sklearn.linear_model import Ridge

# ridge_reg = Ridge(alpha=0.1)
# print("Ridge Regression")
# print("---------------------------------------")
# model_3, mse_3, r_sq_3, rmlse_3 = run_model(ridge_reg, x_train, y_train, x_val, y_val)

Ridge Regression
---------------------------------------
Mean Squared Error Value : 0.06

R-Squared Value : 0.58

RMLSE : 0.25


In [72]:
# import lightgbm as lgb
# # import numpy as np
# from sklearn.model_selection import GridSearchCV

# # create a LightGBM classification
# lgbm_reg = lgb.LGBMRegressor()
# print("LGBM Regression")
# print("---------------------------------------")


# # Define the grid
# param_grid = {
#     'learning_rate': [0.01, 0.1, 0.2],
#     'n_estimators': [20, 40, 60],
#     'num_leaves': [15, 31, 63],
#     'max_depth': [3, 5, 7]
# }

# # Use GridSearchCV to improve the data
# grid = GridSearchCV(lgbm_reg, param_grid, cv=5)


# model_4, mse_4, r_sq_4, rmlse_4 = run_model(grid, x_train, y_train, x_val, y_val)

# # To print the best combination of data
# print("Best parameters found: ", grid.best_params_)

LGBM Regression
---------------------------------------
Mean Squared Error Value : 0.01

R-Squared Value : 0.95

RMLSE : 0.08
Best parameters found:  {'learning_rate': 0.2, 'max_depth': 7, 'n_estimators': 60, 'num_leaves': 63}


In [81]:
from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor()
print("RandomForest Regression")
print("---------------------------------------")
model_5, mse_4, r_sq_4, rmlse_4 = run_model(rf_reg,x_train, y_train, x_val, y_val)

RandomForest Regression
---------------------------------------
Mean Squared Error Value : 0.00

R-Squared Value : 0.99

RMLSE : 0.03


In [82]:
y_pred = model_5.predict(x_test)
y_pred2 = np.exp(y_pred)

In [83]:
 for i in range(len(y_test)):
        print("Expected:", y_test[i], "Predicted:", y_pred2[i])

Expected: 172600 Predicted: 168988.34609311674
Expected: 133100 Predicted: 137101.82544812228
Expected: 171700 Predicted: 166813.23279219476
Expected: 176700 Predicted: 176510.24682097876
Expected: 138332 Predicted: 138710.14573936525
Expected: 131900 Predicted: 128697.72540242755
Expected: 127400 Predicted: 128164.33876400995
Expected: 228700 Predicted: 224395.6086667596
Expected: 70000 Predicted: 67192.26554143893
Expected: 155800 Predicted: 153166.1800726901
Expected: 341500 Predicted: 344234.71544064116
Expected: 402832 Predicted: 399160.1916000635
Expected: 180300 Predicted: 184713.77428792062
Expected: 136900 Predicted: 132128.44532876578
Expected: 194050 Predicted: 191705.612995969
Expected: 217800 Predicted: 219926.6018075913
Expected: 81700 Predicted: 80427.43227711288
Expected: 249800 Predicted: 244798.16338259375
Expected: 194700 Predicted: 185761.4685034952
Expected: 88400 Predicted: 87528.43797767807
Expected: 132400 Predicted: 128532.23750458185
Expected: 197000 Predicted

In [85]:
y_test[:5]
y_pred2[:5]

array([168988.34609312, 137101.82544812, 166813.23279219, 176510.24682098,
       138710.14573937])

In [86]:
results_df = pd.DataFrame({'true_values': y_test, 'predicted_values': y_pred2})

# 相关性
correlation = results_df['true_values'].corr(results_df['predicted_values'])
correlation

0.9979391586975899

In [88]:
y_pre_df = pd.DataFrame(y_pred2, columns=['predicted_revenue'])
y_pre_df.to_csv('z5355268.PART1.output.csv', index=False)